import scala.language.experimental.collectionLiterals
import scala.language.experimental.recordLiterals
import scala.language.experimental.companionScopeInference

// Benchmark for data literals composed with companion scope inference:
// an 800-entry map literal with bare enum keys (receiver-position rule)
// and nested collection literals, plus an 800-element vector of record
// literals. Compare against dataLiteralsVanilla.scala, the same data in
// vanilla syntax.

enum Color:
  case Red, Green, Blue, Cyan, Magenta, Yellow, Black, White

enum Geometry:
  case Circle, Rectangle, Triangle, Square, Pentagon, Hexagon

case class Shape(geometry: Geometry, color: Color = Color.Red)

object Data:
  val byColor: Map[Color, List[Geometry]] = [
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle],
    Red -> [Triangle, Square],
    Green -> [Square, Pentagon],
    Blue -> [Pentagon, Hexagon],
    Cyan -> [Hexagon, Circle],
    Magenta -> [Circle, Rectangle],
    Yellow -> [Rectangle, Triangle],
    Black -> [Triangle, Square],
    White -> [Square, Pentagon],
    Red -> [Pentagon, Hexagon],
    Green -> [Hexagon, Circle],
    Blue -> [Circle, Rectangle],
    Cyan -> [Rectangle, Triangle],
    Magenta -> [Triangle, Square],
    Yellow -> [Square, Pentagon],
    Black -> [Pentagon, Hexagon],
    White -> [Hexagon, Circle],
    Red -> [Circle, Rectangle],
    Green -> [Rectangle, Triangle],
    Blue -> [Triangle, Square],
    Cyan -> [Square, Pentagon],
    Magenta -> [Pentagon, Hexagon],
    Yellow -> [Hexagon, Circle],
    Black -> [Circle, Rectangle],
    White -> [Rectangle, Triangle]]

  val shapes: Vector[Shape] = [
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White),
    (geometry = Triangle, color = Red),
    (geometry = Square, color = Green),
    (geometry = Pentagon, color = Blue),
    (geometry = Hexagon, color = Cyan),
    (geometry = Circle, color = Magenta),
    (geometry = Rectangle, color = Yellow),
    (geometry = Triangle, color = Black),
    (geometry = Square, color = White),
    (geometry = Pentagon, color = Red),
    (geometry = Hexagon, color = Green),
    (geometry = Circle, color = Blue),
    (geometry = Rectangle, color = Cyan),
    (geometry = Triangle, color = Magenta),
    (geometry = Square, color = Yellow),
    (geometry = Pentagon, color = Black),
    (geometry = Hexagon, color = White),
    (geometry = Circle, color = Red),
    (geometry = Rectangle, color = Green),
    (geometry = Triangle, color = Blue),
    (geometry = Square, color = Cyan),
    (geometry = Pentagon, color = Magenta),
    (geometry = Hexagon, color = Yellow),
    (geometry = Circle, color = Black),
    (geometry = Rectangle, color = White)]
