// Benchmark: the same data as dataLiterals.scala in vanilla syntax,
// for comparing the compilation cost of data literals + companion scope
// inference against explicit constructors.

enum Color:
  case Red, Green, Blue, Cyan, Magenta, Yellow, Black, White

enum Geometry:
  case Circle, Rectangle, Triangle, Square, Pentagon, Hexagon

case class Shape(geometry: Geometry, color: Color = Color.Red)

object Data:
  val byColor: Map[Color, List[Geometry]] = Map(
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Red -> List(Geometry.Triangle, Geometry.Square),
    Color.Green -> List(Geometry.Square, Geometry.Pentagon),
    Color.Blue -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Cyan -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Magenta -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Yellow -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Black -> List(Geometry.Triangle, Geometry.Square),
    Color.White -> List(Geometry.Square, Geometry.Pentagon),
    Color.Red -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Green -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Blue -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Cyan -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Magenta -> List(Geometry.Triangle, Geometry.Square),
    Color.Yellow -> List(Geometry.Square, Geometry.Pentagon),
    Color.Black -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.White -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Red -> List(Geometry.Circle, Geometry.Rectangle),
    Color.Green -> List(Geometry.Rectangle, Geometry.Triangle),
    Color.Blue -> List(Geometry.Triangle, Geometry.Square),
    Color.Cyan -> List(Geometry.Square, Geometry.Pentagon),
    Color.Magenta -> List(Geometry.Pentagon, Geometry.Hexagon),
    Color.Yellow -> List(Geometry.Hexagon, Geometry.Circle),
    Color.Black -> List(Geometry.Circle, Geometry.Rectangle),
    Color.White -> List(Geometry.Rectangle, Geometry.Triangle))

  val shapes: Vector[Shape] = Vector(
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White),
    Shape(Geometry.Triangle, Color.Red),
    Shape(Geometry.Square, Color.Green),
    Shape(Geometry.Pentagon, Color.Blue),
    Shape(Geometry.Hexagon, Color.Cyan),
    Shape(Geometry.Circle, Color.Magenta),
    Shape(Geometry.Rectangle, Color.Yellow),
    Shape(Geometry.Triangle, Color.Black),
    Shape(Geometry.Square, Color.White),
    Shape(Geometry.Pentagon, Color.Red),
    Shape(Geometry.Hexagon, Color.Green),
    Shape(Geometry.Circle, Color.Blue),
    Shape(Geometry.Rectangle, Color.Cyan),
    Shape(Geometry.Triangle, Color.Magenta),
    Shape(Geometry.Square, Color.Yellow),
    Shape(Geometry.Pentagon, Color.Black),
    Shape(Geometry.Hexagon, Color.White),
    Shape(Geometry.Circle, Color.Red),
    Shape(Geometry.Rectangle, Color.Green),
    Shape(Geometry.Triangle, Color.Blue),
    Shape(Geometry.Square, Color.Cyan),
    Shape(Geometry.Pentagon, Color.Magenta),
    Shape(Geometry.Hexagon, Color.Yellow),
    Shape(Geometry.Circle, Color.Black),
    Shape(Geometry.Rectangle, Color.White))
